name: Integration

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
    with:
      gate: integration
